### ISSUE TITLE
Feature: ignore SSL verification

### ISSUE THREAD

**Issue by Filirom1** [taraslayshchuk/es2csv#24]
Hello,

When ElasticSearch is behind a Reverse Proxy (Nginx) with self-signed certificates, es2csv is failing with this error:

```
Traceback (most recent call last):
  File "/usr/bin/es2csv", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/es2csv.py", line 277, in main
    es.create_connection()
  File "/usr/lib/python2.7/site-packages/es2csv.py", line 40, in f_retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/es2csv.py", line 74, in create_connection
    es = elasticsearch.Elasticsearch(self.opts.url, timeout=CONNECTION_TIMEOUT, http_auth=self.opts.auth)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 171, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 108, in __init__
    self.set_connections(hosts)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 161, in set_connections
    connections = map(_create_connection, hosts)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 160, in _create_connection
    return self.connection_class(**kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 78, in __init__
    raise ImproperlyConfigured("Root certificates are missing for certificate "
elasticsearch.exceptions.ImproperlyConfigured: Root certificates are missing for certificate validation. Either pass them in using the ca_certs parameter or install certifi to use it automatically.
```

**Comment by taraslayshchuk** [comment]
Hello, @Filirom1, could you please upgrade and try again?
