### ISSUE TITLE
Installing from PyPI with pip is broken

### ISSUE THREAD

**Issue by jruere** [taraslayshchuk/es2csv#33]
The error is:

```
Collecting es2csv
  Downloading es2csv-5.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5t9_3isy/es2csv/setup.py", line 26, in <module>
        with open('HISTORY.rst') as history_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5t9_3isy/es2csv/
```

**Comment by taraslayshchuk** [comment]
Hello,

Please provide more information: OS, python version, pip version.

**Comment by jruere** [comment]
Arch Linux
Python 3.6
pip        9.0.1  
setuptools 36.2.0 
wheel      0.29.0

**Comment by jruere** [comment]
Ah, it works on Python 2... Sorry.

**Comment by taraslayshchuk** [comment]
Could you please use python2.7? Python3 is not supported at the moment.

**Comment by taraslayshchuk** [comment]
Yeah, fresh install on ubuntu 16.04.2:
```root@8a546bddecf5:/# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

root@8a546bddecf5:/# uname -a
Linux 8a546bddecf5 4.8.0-54-generic #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

root@8a546bddecf5:/# pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

root@8a546bddecf5:/# pip install es2csv
Collecting es2csv
  Downloading es2csv-5.2.1-py27-none-any.whl
Collecting progressbar2<3.11.0,>=3.10.0 (from es2csv)
  Downloading progressbar2-3.10.1-py2.py3-none-any.whl
Collecting elasticsearch<5.3.0,>=5.2.0 (from es2csv)
  Downloading elasticsearch-5.2.0-py2.py3-none-any.whl (57kB)
    100% |################################| 61kB 1.2MB/s 
Collecting python-utils>=2.0.0 (from progressbar2<3.11.0,>=3.10.0->es2csv)
  Downloading python_utils-2.1.0-py2.py3-none-any.whl
Collecting urllib3<2.0,>=1.8 (from elasticsearch<5.3.0,>=5.2.0->es2csv)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |################################| 133kB 1.6MB/s 
Collecting six (from python-utils>=2.0.0->progressbar2<3.11.0,>=3.10.0->es2csv)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, python-utils, progressbar2, urllib3, elasticsearch, es2csv
Successfully installed elasticsearch-5.2.0 es2csv-5.2.1 progressbar2-3.10.1 python-utils-2.1.0 six-1.10.0 urllib3-1.22
```
