### ISSUE TITLE
HISTORY.rst isn't included in the distribution

### ISSUE THREAD

**Issue by NicholasRBowers** [taraslayshchuk/es2csv#38]
Don't think that the HISTORY.rst file is included in the distribution.  Installing directly from source works just fine.

```
pip3 install es2csv --user
Collecting es2csv
  Using cached es2csv-5.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-w54tvjbj/es2csv/setup.py", line 26, in <module>
        with open('HISTORY.rst') as history_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
```

**Comment by taraslayshchuk** [comment]
Duplicate #33
