### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by jacol** [taraslayshchuk/es2csv#42]
hi

when running:
**es2csv -i _all -q '*' -o database.csv**

i get error with this output, any hints?

Found 770052 results
Run query [                                                                                                                                                        ] [0/770052] [  0%] [0:00:00] [ETA:  --:--:--] [  0.0 s/docs]GET http://localhost:9200/_search/scroll?scroll=30m [status:400 request:0.002s]
Traceback (most recent call last):
  File "/usr/local/bin/es2csv", line 11, in <module>
    load_entry_point('es2csv==5.2.1', 'console_scripts', 'es2csv')()
  File "/usr/local/lib/python3.5/dist-packages/es2csv.py", line 283, in main
    es.search_query()
  File "/usr/local/lib/python3.5/dist-packages/es2csv.py", line 40, in f_retry
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/es2csv.py", line 177, in search_query
    res = next_scroll(res['_scroll_id'])
  File "/usr/local/lib/python3.5/dist-packages/es2csv.py", line 40, in f_retry
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/es2csv.py", line 93, in next_scroll
    return self.es_conn.scroll(scroll=self.scroll_time, scroll_id=scroll_id)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 955, in scroll
    params=params, body=body)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/base.py", line 122, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: <exception str() failed>

**Comment by taraslayshchuk** [comment]
Please use python2, python3 not supported yet.
