### ISSUE TITLE
Error during pip install

### ISSUE THREAD

**Issue by prihoda** [taraslayshchuk/es2csv#57]
Hi, I cannot seem to install this tool using pip.

I'm running
```
pip install es2csv
```

And I get:
```
Collecting es2csv
  Using cached https://files.pythonhosted.org/packages/3d/3a/6dedac602d4b10022d427a78e9b718a57a7254e02810906b99b41a6e6c72/es2csv-5.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rl/s1n4s2gj6s1g6xbtcb5tbc552g46ml/T/pip-install-_lbj65jn/es2csv/setup.py", line 26, in <module>
        with open('HISTORY.rst') as history_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'

```

**Comment by prihoda** [comment]
Yup this is because I'm installing with python 3. Python 2 is required.
