### ISSUE TITLE
can I export data of aggregation

### ISSUE THREAD

**Issue by iamtiancaif** [taraslayshchuk/es2csv#7]
I wanted to export aggregation data but got this error:

	Traceback (most recent call last):
	  File "/usr/local/bin/es2csv", line 9, in <module>
	    load_entry_point('es2csv==1.0.2', 'console_scripts', 'es2csv')()
	  File "/usr/local/lib/python2.7/dist-packages/es2csv.py", line 265, in main
	    es.search_query()
	  File "/usr/local/lib/python2.7/dist-packages/es2csv.py", line 39, in f_retry
	    return f(*args, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/es2csv.py", line 106, in search_query
	    query = json.loads(self.opts.query)
	  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
	    return _default_decoder.decode(s)
	  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
	    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
	    obj, end = self.scan_once(s, idx)
	ValueError: Expecting property name: line 76 column 29 (char 2482)

Thanks~

**Comment by taraslayshchuk** [comment]
Could you please provide more information about query? Did you try to use [curl](https://www.elastic.co/guide/en/elasticsearch/reference/current/_executing_aggregations.html) for your query? Maybe you have some mistakes there?
As I see you have been using version 1.0.2:
>     load_entry_point('es2csv==1.0.2', 'console_scripts', 'es2csv')()

Could you please update to 1.0.3 (this includes elasticsearch-py api upgrade from 1.4 to 2.3)?
Based on this stacktrace I am guessing that probably you have problem with your query in json:

>   File "/usr/local/lib/python2.7/dist-packages/es2csv.py", line 106, in search_query
    query = json.loads(self.opts.query)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

Looks like it fails when trying to parse json.

**Comment by ivantichy** [comment]
OK, so is there possibility to export data from aggregations ? :)

**Comment by vvitryk** [comment]
Hi Taras, i have a similar problem, please share the correct syntax to export data from aggregations. Thanks.
